linters:
  enable:
    - golint

linters-settings:
  golint:
    min-confidence: 0

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude comments on test functions
    - path: _test\.go
      text: "should have comment or be unexported"

